class Design < ActiveHash::Base
  self.data = [
   { id: 1, name: '---' },
   { id: 2, name: 'フレンチネイル' },
   { id: 3, name: 'グラデーションネイル' },
   { id: 4, name: 'ワンカラーネイル' },
   { id: 5, name: 'フラワーネイル' },
   { id: 6, name: 'ストーンネイル' },
   { id: 7, name: 'タイダイネイル' },
   { id: 8, name: 'フットネイル' },
   { id: 9, name: 'アイシングネイル' },
   { id: 10, name: 'アニマル柄ネイル' },
   { id: 11, name: 'アンティークネイル' },
   { id: 12, name: '痛ネイル' },
   { id: 13, name: 'イニシャルネイル' },
   { id: 14, name: 'エスニックネイル' },
   { id: 15, name: 'カモフラージュネイル' },
   { id: 16, name: '逆フレンチネイル' },
   { id: 17, name: 'キャラクターネイル' },
   { id: 18, name: '金箔ネイル' },
   { id: 19, name: 'キルティングネイル' },
   { id: 20, name: 'クリアネイル' },
   { id: 21, name: 'シースルーネイル' },
   { id: 22, name: 'シールネイル' },
   { id: 23, name: 'シェルネイル' },
   { id: 24, name: 'スイーツネイル' },
   { id: 25, name: '水滴ネイル' },
   { id: 26, name: 'スタッズネイル' },
   { id: 27, name: 'スターネイル' },
   { id: 28, name: 'ストライプネイル' },
   { id: 29, name: 'スパンコールネイル' },
   { id: 30, name: '３Dネイル' },
   { id: 31, name: '大理石風ネイル' },
   { id: 32, name: 'チークネイル' },
   { id: 33, name: 'チェックネイル' },
   { id: 34, name: '千鳥格子ネイル' },
   { id: 35, name: 'ツイードネイル' },
   { id: 36, name: 'デコネイル' },
   { id: 37, name: 'デニムネイル' },
   { id: 38, name: 'ドットネイル' },
   { id: 39, name: 'ニットネイル' },
   { id: 40, name: 'ニュアンスネイル' },
   { id: 41, name: 'バイカラーネイル' },
   { id: 42, name: 'ハートネイル' },
   { id: 43, name: 'ビジューネイル' },
   { id: 44, name: 'フルーツネイル' },
   { id: 45, name: 'ブローチネイル' },
   { id: 46, name: 'べっこうネイル' },
   { id: 47, name: 'マグネットネイル' },
   { id: 48, name: 'マーブルネイル' },
   { id: 49, name: 'マーメイドネイル' },
   { id: 50, name: 'マットネイル' },
   { id: 51, name: 'ミラーネイル' },
   { id: 52, name: '雪の結晶ネイル' },
   { id: 53, name: 'ラメネイル' },
   { id: 54, name: 'リボンネイル' },
   { id: 55, name: 'レースネイル' },
   { id: 56, name: 'その他' }
 ]

 include ActiveHash::Associations
  has_many :nails
 end